<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class orderInfo extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $orders = [
            [
                'username' => 'john_doe',
                'userid' => 3,
                'user_email' => 'john@example.com',
                'fname' => 'John',
                'lname' => 'Doe',
                'products' => 'Product A, Product B',
                'qty' => '2, 3',
                'phone' => '1234567890',
                'email' => 'john_doe@example.com',
                'address' => '123 Main Street',
                'city' => 'New York',
                'state' => 'NY',
                'zipcode' => '10001',
                'subtotal' => 100.00,
                'tax' => 10.00,
                'total' => 110.00,
                'payment_option' => 'Credit Card',
                'status'=>0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Add 10 more users
            [
                'username' => 'jane_smith',
                'userid' => 4,
                'user_email' => 'jane@example.com',
                'fname' => 'Jane',
                'lname' => 'Smith',
                'products' => 'Product C, Product D',
                'qty' => '1, 2',
                'phone' => '9876543210',
                'email' => 'jane_smith@example.com',
                'address' => '456 Elm Street',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'zipcode' => '90001',
                'subtotal' => 80.00,
                'tax' => 8.00,
                'total' => 88.00,
                'payment_option' => 'PayPal',
                'status'=>1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'username' => 'alex_walker',
                'userid' => 5,
                'user_email' => 'alex@example.com',
                'fname' => 'Alex',
                'lname' => 'Walker',
                'products' => 'Product E',
                'qty' => '1',
                'phone' => '5551234567',
                'email' => 'alex_walker@example.com',
                'address' => '789 Oak Street',
                'city' => 'Chicago',
                'state' => 'IL',
                'zipcode' => '60601',
                'subtotal' => 50.00,
                'tax' => 5.00,
                'total' => 55.00,
                'payment_option' => 'Credit Card',
                'status'=>0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'username' => 'sarah_jones',
                'userid' => 6,
                'user_email' => 'sarah@example.com',
                'fname' => 'Sarah',
                'lname' => 'Jones',
                'products' => 'Product F, Product G, Product H',
                'qty' => '1, 2, 1',
                'phone' => '2229876543',
                'email' => 'sarah_jones@example.com',
                'address' => '321 Pine Street',
                'city' => 'Seattle',
                'state' => 'WA',
                'zipcode' => '98101',
                'subtotal' => 150.00,
                'tax' => 15.00,
                'total' => 165.00,
                'payment_option' => 'PayPal',
                'status'=>1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'username' => 'mark_anderson',
                'userid' => 7,
                'user_email' => 'mark@example.com',
                'fname' => 'Mark',
                'lname' => 'Anderson',
                'products' => 'Product I, Product J',
                'qty' => '2, 2',
                'phone' => '9995551234',
                'email' => 'mark_anderson@example.com',
                'address' => '567 Maple Street',
                'city' => 'San Francisco',
                'state' => 'CA',
                'zipcode' => '94101',
                'subtotal' => 120.00,
                'tax' => 12.00,
                'total' => 132.00,
                'status'=>0,
                'payment_option' => 'Credit Card',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'username' => 'emily_smith',
                'userid' => 8,
                'user_email' => 'emily@example.com',
                'fname' => 'Emily',
                'lname' => 'Smith',
                'products' => 'Product K',
                'qty' => '1',
                'phone' => '7772223333',
                'email' => 'emily_smith@example.com',
                'address' => '890 Elm Street',
                'city' => 'Boston',
                'state' => 'MA',
                'zipcode' => '02101',
                'subtotal' => 40.00,
                'tax' => 4.00,
                'total' => 44.00,
                'payment_option' => 'PayPal',
                'status'=>0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'username' => 'michael_brown',
                'userid' => 9,
                'user_email' => 'michael@example.com',
                'fname' => 'Michael',
                'lname' => 'Brown',
                'products' => 'Product L, Product M, Product N',
                'qty' => '1, 3, 2',
                'phone' => '8884445555',
                'email' => 'michael_brown@example.com',
                'address' => '111 Oak Street',
                'city' => 'Miami',
                'state' => 'FL',
                'zipcode' => '33101',
                'subtotal' => 180.00,
                'tax' => 18.00,
                'total' => 198.00,
                'payment_option' => 'Credit Card',
                'status'=>0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'amy_wilson',
                'userid' => 10,
                'user_email' => 'amy@example.com',
                'fname' => 'Amy',
                'lname' => 'Wilson',
                'products' => 'Product O',
                'qty' => '1',
                'phone' => '5551112222',
                'email' => 'amy_wilson@example.com',
                'address' => '222 Elm Street',
                'city' => 'Denver',
                'state' => 'CO',
                'zipcode' => '80201',
                'subtotal' => 60.00,
                'tax' => 6.00,
                'total' => 66.00,
                'payment_option' => 'PayPal',
                'status'=>0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'username' => 'robert_johnson',
                'userid' => 11,
                'user_email' => 'robert@example.com',
                'fname' => 'Robert',
                'lname' => 'Johnson',
                'products' => 'Product P, Product Q, Product R',
                'qty' => '1, 2, 1',
                'phone' => '7779991111',
                'email' => 'robert_johnson@example.com',
                'address' => '333 Oak Street',
                'city' => 'Dallas',
                'state' => 'TX',
                'zipcode' => '75201',
                'subtotal' => 130.00,
                'tax' => 13.00,
                'total' => 143.00,
                'payment_option' => 'Credit Card',
                'status'=>0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Add 8 more users with similar structure
        ];
        DB::table('completecheckouts')->insert($orders);
    }
}
